2023-06-01 12:54:25,209 INFO    MainThread:13452 [wandb_setup.py:_flush():76] Current SDK version is 0.15.3
2023-06-01 12:54:25,209 INFO    MainThread:13452 [wandb_setup.py:_flush():76] Configure stats pid to 13452
2023-06-01 12:54:25,209 INFO    MainThread:13452 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Hamid Jahani\.config\wandb\settings
2023-06-01 12:54:25,209 INFO    MainThread:13452 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Hamid Jahani\Documents\MLOps-Zoomcamp-Course\02-experiment-tracking\Wandb\wandb\settings
2023-06-01 12:54:25,209 INFO    MainThread:13452 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-06-01 12:54:25,209 INFO    MainThread:13452 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-06-01 12:54:25,209 INFO    MainThread:13452 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': '02-experiment-tracking\\Wandb\\preprocess_data.py', 'program': 'C:\\Users\\Hamid Jahani\\Documents\\MLOps-Zoomcamp-Course\\02-experiment-tracking\\Wandb\\preprocess_data.py'}
2023-06-01 12:54:25,210 INFO    MainThread:13452 [wandb_init.py:_log_setup():507] Logging user logs to C:\Users\Hamid Jahani\Documents\MLOps-Zoomcamp-Course\02-experiment-tracking\Wandb\wandb\run-20230601_125425-balkkxbx\logs\debug.log
2023-06-01 12:54:25,210 INFO    MainThread:13452 [wandb_init.py:_log_setup():508] Logging internal logs to C:\Users\Hamid Jahani\Documents\MLOps-Zoomcamp-Course\02-experiment-tracking\Wandb\wandb\run-20230601_125425-balkkxbx\logs\debug-internal.log
2023-06-01 12:54:25,210 INFO    MainThread:13452 [wandb_init.py:init():547] calling init triggers
2023-06-01 12:54:25,210 INFO    MainThread:13452 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-06-01 12:54:25,210 INFO    MainThread:13452 [wandb_init.py:init():596] starting backend
2023-06-01 12:54:25,210 INFO    MainThread:13452 [wandb_init.py:init():600] setting up manager
2023-06-01 12:54:25,215 INFO    MainThread:13452 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-06-01 12:54:25,222 INFO    MainThread:13452 [wandb_init.py:init():606] backend started and connected
2023-06-01 12:54:25,227 INFO    MainThread:13452 [wandb_init.py:init():700] updated telemetry
2023-06-01 12:54:25,266 INFO    MainThread:13452 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-06-01 12:54:26,603 ERROR   MainThread:13452 [wandb_init.py:init():763] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2023-06-01 12:54:28,615 ERROR   MainThread:13452 [wandb_init.py:init():1168] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "C:\Users\Hamid Jahani\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\wandb_init.py", line 1150, in init
    run = wi.init()
  File "C:\Users\Hamid Jahani\AppData\Roaming\Python\Python310\site-packages\wandb\sdk\wandb_init.py", line 769, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2023-06-01 12:54:29,629 WARNING MsgRouterThr:13452 [router.py:message_loop():77] message_loop has been closed
